---
name: Install uv, Python, and project dependencies
description: Install uv, Python, and project dependencies using cached uv and Python installations

inputs:
  python-version:
    description: >
      Version range or exact version of a Python version to use, using SemVer's version range syntax.
    required: false
    default: "3.12"

outputs:
  python-version:
    description: The installed python version. Useful when given a version range as input.
    value: ${{ steps.setup-python.outputs.python-version }}

runs:
  using: composite
  steps:
    - name: Setup uv with cache
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Install the project
      shell: bash
      run: uv sync --all-extras --dev

    - name: Minimize uv cache
      shell: bash
      run: uv cache prune --ci

    # ----------------------------------------------
    #    Install MongoDB Tools
    # ----------------------------------------------

    # - name: Setup mongodb-tools
    #   shell: bash
    #   run: |
    #     https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu1604-x86_64-100.12.2.deb
    #     sudo apt install ./mongodb-database-tools-ubuntu1604-x86_64-100.12.2.deb
