---
name: Install uv, Python, and project dependencies
description: Install uv, Python, and project dependencies using cached uv and Python installations

inputs:
  python-version:
    description: >
      Version range or exact version of a Python version to use, using SemVer's version range syntax.
    required: false
    default: "3.13"

runs:
  using: composite
  steps:
    - name: Setup uv with cache
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        enable-cache: true
        python-version: ${{ inputs.python-version }}

    - name: Install the project
      shell: bash
      run: uv sync --all-extras --dev

    - name: Debug Python version
      shell: bash
      run: |
        echo "Input python-version: ${{ inputs.python-version }}"
        echo "Python version: $(python --version)"
        echo "Python location: $(which python)"
        echo "uv Python version: $(uv python --version)"

    - name: Minimize uv cache
      shell: bash
      run: uv cache prune --ci

    # ----------------------------------------------
    #    Install MongoDB Tools
    # ----------------------------------------------

    # - name: Setup mongodb-tools
    #   shell: bash
    #   run: |
    #     https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu1604-x86_64-100.12.2.deb
    #     sudo apt install ./mongodb-database-tools-ubuntu1604-x86_64-100.12.2.deb
