---
services:
    backup-mongodb:
        build: .
        env_file:
            - .env
        volumes:
            - .dev:/app/.dev

        develop:
            watch:
                - action: sync
                  path: ./src
                  target: /app/src
                - action: rebuild
                  path: ./uv.lock
                  target: /app/uv.lock
                - action: rebuild
                  path: ./pyproject.toml
                  target: /app/pyproject.toml
                - action: rebuild
                  path: ./Dockerfile
