[build-system]
    build-backend = "poetry.core.masonry.api"
    requires      = ["poetry-core>=1.0.0"]

[tool.poetry]
    authors     = ["Nate Landau <github@natenate.org>"]
    description = "Backup MongoDB databases"
    homepage    = "https://github.com/natelandau/backup-mongodb"
    keywords    = []
    license     = ""
    name        = "backup-mongodb"
    readme      = "README.md"
    repository  = "https://github.com/natelandau/backup-mongodb"
    version     = "1.0.0"

    [tool.poetry.scripts] # https://python-poetry.org/docs/pyproject/#scripts
        # backup-mongodb = "backup_mongodb.main:app"
        backup-mongodb = "backup_mongodb.main:main"

    [tool.poetry.dependencies]
        arrow         = "^1.3.0"
        boto3         = "^1.28.84"
        flask         = "^3.0.0"
        inflect       = "^7.0.0"
        loguru        = "^0.7.2"
        python        = "^3.11"
        python-dotenv = "^1.0.0"
        requests      = "^2.31.0"
        rich          = "^13.6.0"
        schedule      = "^1.2.1"
        sh            = "^2.0.6"

    [tool.poetry.group.test.dependencies]
        freezegun              = "^1.2.2"
        pytest                 = "^7.4.3"
        pytest-asyncio         = "^0.21.1"
        pytest-clarity         = "^1.0.1"
        pytest-env             = "^1.1.1"
        pytest-mock            = "^3.12.0"
        pytest-pretty-terminal = "^1.1.0"
        pytest-xdist           = "^3.4.0"

    [tool.poetry.group.dev.dependencies]
        commitizen    = "^3.12.0"
        coverage      = "^7.3.2"
        mypy          = "^1.7.0"
        pdoc          = "^14.1.0"
        poethepoet    = "^0.22.1"
        pre-commit    = "^3.5.0"
        ruff          = "^0.1.5"
        shellcheck-py = "^0.9.0.5"
        typos         = "^1.16.23"
        vulture       = "^2.10"
        yamllint      = "^1.33.0"

[tool.commitizen]
    bump_message               = "bump(release): v$current_version → v$new_version"
    changelog_merge_prerelease = true
    tag_format                 = "v$version"
    update_changelog_on_bump   = true
    version                    = "1.0.0"
    version_files              = ["pyproject.toml:version", "src/backup_mongodb/__version__.py:__version__"]

[tool.coverage.report] # https://coverage.readthedocs.io/en/latest/config.html#report
    exclude_lines = [
        'def __repr__',
        'except [\w\s\._]+ as .*:',
        'log\.critical',
        'log\.debug',
        'log\.error',
        'log\.exception',
        'log\.info',
        'log\.success',
        'log\.trace',
        'log\.warning',
        'pragma: no cover',
        'raise Abort',
        'raise Exit',
        'raise typer\.Exit',
    ]
    fail_under = 10
    precision = 1
    show_missing = true
    skip_covered = true

[tool.coverage.run]
    branch       = true
    command_line = "--module pytest"
    data_file    = "reports/.coverage"
    source       = ["src"]

[tool.coverage.xml]
    output = "reports/coverage.xml"

[tool.interrogate]
    exclude            = ["build", "docs", "tests"]
    fail-under         = 90
    ignore-init-method = true
    verbose            = 2

[tool.mypy] # https://mypy.readthedocs.io/en/latest/config_file.html
    disallow_any_unimported = false
    disallow_subclassing_any = false
    disallow_untyped_decorators = false
    disallow_untyped_defs = true
    exclude = [
        'tests/', # TOML literal string (single-quotes, regex okay, no escaping necessary)
    ]
    follow_imports = "normal"
    ignore_missing_imports = true
    junit_xml = "reports/mypy.xml"
    no_implicit_optional = true
    pretty = false
    show_column_numbers = true
    show_error_codes = true
    show_error_context = true
    strict_optional = false
    warn_redundant_casts = true
    warn_unreachable = true
    warn_unused_ignores = true

[tool.pytest.ini_options]
    addopts        = "--color=yes --doctest-modules --exitfirst --failed-first --strict-config --strict-markers --verbosity=2 --junitxml=reports/pytest.xml"
    asyncio_mode   = "auto"
    filterwarnings = ["error", "ignore::DeprecationWarning"]
    testpaths      = ["src", "tests"]
    xfail_strict   = true

[tool.ruff] # https://github.com/charliermarsh/ruff
    exclude = [
        ".bzr",
        ".direnv",
        ".eggs",
        ".git",
        ".hg",
        ".mypy_cache",
        ".nox",
        ".pants.d",
        ".pytype",
        ".ruff_cache",
        ".svn",
        ".tox",
        ".venv",
        "__pypackages__",
        "_build",
        "buck-out",
        "build",
        "dist",
        "node_modules",
        # "src/valentina/cogs/test_cog.py",
        "venv",
    ]
    # Avoiding flagging (and removing) `V101` from any `# noqa`
    # directives, despite Ruff's lack of support for `vulture`.
    external = ["V"]
    fix = true
    ignore = [
        "B006",
        "B008",
        "D107",
        "D203",
        "D204",
        "D213",
        "D215",
        "D404",
        "D406",
        "D407",
        "D408",
        "D409",
        "D413",
        "E266",
        "E501",
        "ISC001",
        "N805",
        "PGH001",
        "PGH003",
        "PLR0913",
        "PLR0917",
        "S311",
        "UP007",
    ]
    ignore-init-module-imports = true
    line-length = 100
    output-format = "grouped"
    per-file-ignores = { "cli.py" = [
        "PLR0912",
        "PLR0913",
    ], "tests/*.py" = [
        "A002",
        "A003",
        "D102",
        "F403",
        "PLR0913",
        "PLR2004",
        "S101",
    ] }
    preview = true
    select = [
        "A",     # flake8-builtins
        "ARG",   # flake8-unused-arguments
        "ASYNC", # flake8-async
        "B",     # flake8-bugbear
        "BLE",   # flake8-blind-exception
        "C4",    # flake8-comprehensions
        "C90",   # McCabe
        "D",     # pydocstyle
        "E",     # pycodestyle Errors
        "EM",    # flake8-errmsg
        "ERA",   # flake8-eradicate
        "EXE",   # flake8-executable
        "F",     # pyflakes
        "FA",    # flake8-future
        "FLY",   # flynt
        "FURB",  # refurb
        "I",     # iSort
        "ISC",   # flake8-implicit-str-concat
        "N",     # Pep8-naming
        "NPY",   # flake8-numpy
        "PERF",  # Perflint
        "PGH",   # pygrep-hooks
        "PL",    # pylint
        "PLC",   # pylint Convention
        "PLE",   # pylint Error
        "PLR",   # pylint Refactor
        "PLW",   # pylint Warning
        "PT",    # flake8-pytest-style
        "PTH",   # flake8-use-pathlib
        "Q",     # flake8-quotes
        "RET",   # flake8-return
        "RUF",   # Ruff-specific rules
        "S",     # flake8-bandit
        "SIM",   # flake8-simplify
        "T20",   # flake8-print
        "TID",   # flake8-tidy-imports
        "TRY",   # tryceratops
        "UP",    # pyupgrade
        "W",     # pycodestyle Warnings
        "YTT",   # flake8-2020
        # "DTZ",   # flake8-datetimez
    ]
    src = ["src", "tests"]
    target-version = "py311"
    unfixable = ["E712", "ERA001", "F401", "F841", "UP007"]

    [tool.ruff.mccabe]
        # Unlike Flake8, default to a complexity level of 10.
        max-complexity = 10

    [tool.ruff.pydocstyle]
        convention = "google"

    [tool.ruff.pylint]
        max-args = 6

    [tool.ruff.format]
        indent-style              = "space"
        line-ending               = "auto"
        quote-style               = "double"
        skip-magic-trailing-comma = false

[tool.vulture] # https://pypi.org/project/vulture/
    # exclude = ["file*.py", "dir/"]
    # ignore_decorators = ["@app.route", "@require_*"]
    ignore_names = ["args", "kwargs", "request", "version"]
    # make_whitelist = true
    min_confidence = 80
    paths          = ["src", "tests"]
    sort_by_size   = true
    verbose        = false

[tool.poe.tasks]

    [tool.poe.tasks.docs]
        cmd = """
    pdoc
      --docformat google
      --output-directory docs
      src/backup_mongodb
    """
        help = "Generate this package's docs"

    [tool.poe.tasks.lint]
        help = "Lint this package"

        [[tool.poe.tasks.lint.sequence]]
            shell = "ruff --preview --no-fix src/"

        [[tool.poe.tasks.lint.sequence]]
            shell = "ruff format --check src/ tests/"

        [[tool.poe.tasks.lint.sequence]]
            shell = "poetry check"

        [[tool.poe.tasks.lint.sequence]]
            shell = "mypy --config-file pyproject.toml src/"

        [[tool.poe.tasks.lint.sequence]]
            shell = "typos"

        [[tool.poe.tasks.lint.sequence]]
            shell = "vulture src/ tests/ --exclude src/valentina/cogs/test_cog.py"

        [[tool.poe.tasks.lint.sequence]]
            shell = "yamllint ."

[tool.poe.tasks.test]
    help = "Test this package"

    [[tool.poe.tasks.test.sequence]]
        cmd = "coverage run"

    [[tool.poe.tasks.test.sequence]]
        cmd = "coverage report"

    [[tool.poe.tasks.test.sequence]]
        cmd = "coverage xml"
