---
name: "Reusable Tests"

on:
    workflow_call:
        inputs:
            run-coverage:
                description: "Run coverage"
                required: false
                type: boolean
                default: false

jobs:
    test-python-code:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.13"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Python, uv, and the package
              uses: ./.github/actions/setup_python_env
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Run tests
              shell: bash
              run: uv run duty test

            - name: Upload coverage to Codecov
              if: ${{ inputs.run-coverage && matrix.python-version == '3.13' }}
              uses: codecov/codecov-action@v5
              with:
                  files: .cache/coverage.xml
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    lint-project:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: actions/cache@v4
              with:
                  path: ~/.cache/pre-commit
                  key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

            - name: Setup Python, uv, and the package
              uses: ./.github/actions/setup_python_env

            - name: run all linters
              shell: bash
              run: uv run duty lint

    test-build-container:
        if: ${{ !contains(github.event.head_commit.message, 'bump(release)') }}
        runs-on: ubuntu-latest
        needs:
            - test-python-code
            - lint-project
        permissions:
            contents: read
            packages: write
        env:
            REGISTRY: ghcr.io
            IMAGE_NAME: ${{ github.repository }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2 # Need at least 2 commits to compare

            - name: Check if Dockerfile changed
              id: dockerfile-changes
              run: |
                  if git diff --name-only HEAD~1 HEAD | grep -q "^Dockerfile$"; then
                    echo "dockerfile=true" >> $GITHUB_OUTPUT
                  else
                    echo "dockerfile=false" >> $GITHUB_OUTPUT
                  fi

            - name: Set up QEMU
              if: steps.dockerfile-changes.outputs.dockerfile == 'true'
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              if: steps.dockerfile-changes.outputs.dockerfile == 'true'
              uses: docker/setup-buildx-action@v3

            - name: Build multi-arch Docker image
              if: steps.dockerfile-changes.outputs.dockerfile == 'true'
              uses: docker/build-push-action@v6
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  outputs: type=cacheonly
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  tags: user/app:latest
