---
name: "Upload to Codecov"

on:
    workflow_dispatch:
    workflow_run:
        workflows: ["Automated Tests"]
        types:
            - completed
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    upload-coverage:
        runs-on: ubuntu-latest

        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.11"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            # ----------------------------------------------
            # Setup Python, uv, and install project dependencies
            # ----------------------------------------------

            - name: Setup Python, uv, and the package
              uses: ./.github/actions/uv-python-package

            # ----------------------------------------------
            # Run tests
            # ----------------------------------------------

            - name: Run tests with pytest
              run: |
                  uv run coverage run
                  uv run coverage report
                  uv run coverage xml

            # ----------------------------------------------
            #             upload coverage stats
            # ----------------------------------------------

            - name: Upload coverage
              uses: codecov/codecov-action@v5
              with:
                  files: reports/coverage.xml
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo 'The triggering workflow failed'
